### ISSUE TITLE
Defining anonymous classes at runtime is not supported.

### ISSUE THREAD

**Issue by fabioloreggian** [Nithanim/quarkus-dynamodb-enhanced#4]
Hi there,

I am having a problem when running my function.

Here is the error I get:

```Skip pulling image and use local one: public.ecr.aws/sam/emulation-provided:rapid-1.37.0-x86_64.

Mounting /tmp/tmpdiy2yp68 as /var/task:ro,delegated inside runtime container
START RequestId: 9e1549f3-48ca-4020-94f2-60c153428d4f Version: $LATEST
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-01-14 09:30:34,013 WARN  [io.qua.application] (main) Setting the 'javax.net.ssl.trustStore' system property will not have any effect at runtime. Make sure to set this property at build time (for example by setting 'quarkus.native.additional-build-args=-J-Djavax.net.ssl.trustStore=someValue').
2022-01-14 09:30:34,039 INFO  [io.quarkus] (main) iam 1.0-SNAPSHOT native (powered by Quarkus 2.5.0.Final) started in 0.026s. 
2022-01-14 09:30:34,040 INFO  [io.quarkus] (main) Profile prod activated. 
2022-01-14 09:30:34,040 INFO  [io.quarkus] (main) Installed features: [amazon-dynamodb, amazon-lambda, amazon-s3, amazon-ses, amazon-sns, aws-dynamodb-enhanced, cdi]
2022-01-14 09:30:34,398 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (NORMAL)) Failed to run lambda (NORMAL): java.lang.IllegalArgumentException: Failed to generate method handle.
        at software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder.build(LambdaToMethodBridgeBuilder.java:92)
        at software.amazon.awssdk.enhanced.dynamodb.internal.mapper.ObjectConstructor.create(ObjectConstructor.java:37)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.newObjectSupplierForClass(BeanTableSchema.java:361)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:172)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:129)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:121)
        at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromBean(TableSchema.java:81)
        at com.loreggian.invflow.common.services.organization.OrganizationService.getDynamoDbTable(OrganizationService.java:52)
        at com.loreggian.invflow.common.services.DynamoDbService.getDynamoDbTable(DynamoDbService.java:50)
        at com.loreggian.invflow.common.services.organization.OrganizationService.createOrganization(OrganizationService.java:66)
        at com.loreggian.invflow.common.services.organization.OrganizationService_ClientProxy.createOrganization(OrganizationService_ClientProxy.zig:1200)
        at com.loreggian.invflow.iam.organization.CreateOrganization.handleRequest(CreateOrganization.java:34)
        at com.loreggian.invflow.iam.organization.CreateOrganization.handleRequest(CreateOrganization.java:16)
        at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:161)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:124)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: com.oracle.svm.core.jdk.UnsupportedFeatureError: Defining anonymous classes at runtime is not supported.
        at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:87)
        at jdk.internal.misc.Unsafe.defineAnonymousClass(Unsafe.java:213)
        at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:302)
        at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:193)
        at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:329)
        at software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder.build(LambdaToMethodBridgeBuilder.java:83)
        ... 17 more

{"errorType":"java.lang.IllegalArgumentException","errorMessage":"Failed to generate method handle."}END RequestId: 9e1549f3-48ca-4020-94f2-60c153428d4f
REPORT RequestId: 9e1549f3-48ca-4020-94f2-60c153428d4f  Init Duration: 0.59 ms  Duration: 423.50 ms     Billed Duration: 424 ms Memory Size: 128 MB     Max Memory Used: 128 MB
```

After looking at the LambdaToMethodBridgeBuilder code it looks to be breaking on this method call:
```
public T build() {
        try {
            MethodHandle targetMethodHandle = targetMethod.map(
                m -> invokeSafely(() -> LOOKUP.unreflect(m)),
                c -> invokeSafely(() -> LOOKUP.unreflectConstructor(c)));

            return lambdaType.cast(
                LambdaMetafactory.metafactory(LOOKUP,
                                              lambdaMethodName,
                                              MethodType.methodType(lambdaType),
                                              MethodType.methodType(postEraseLambdaReturnType, postEraseLambdaParameters),
                                              targetMethodHandle,
                                              MethodType.methodType(preEraseLambdaReturnType, preEraseLambdaParameters))
                                 .getTarget()
                                 .invoke());
        } catch (Throwable e) {
            throw new IllegalArgumentException("Failed to generate method handle.", e);
        }
    }
```

Can you possibly point me in the right direction?

**Comment by Nithanim** [comment]
Hello!
Thank you for reporting your issue! I have honestly no idea why it would work before and not now. Though, I did recreate your problem and released a fix. The issue should be fixed in version `1.0.1`. It may take some time to propagate to maven central. Please report any issues you might encounter!

**Comment by fabioloreggian** [comment]
When I can see the release on maven, I will pull and try it out. Thank you for the speedy response.

**Comment by Nithanim** [comment]
No problem!
You might be able to pull before the index and web-interface have updated.
E.g. https://repo1.maven.org/maven2/me/nithanim/quarkus/quarkus-amazon-dynamodb-enhanced/1.0.1/quarkus-amazon-dynamodb-enhanced-1.0.1.jar

**Comment by fabioloreggian** [comment]
It is now working. Thank you for your help

**Comment by Nithanim** [comment]
Glad it works for you now. Thank you for reporting!
